// r2-client.mjs — Cloudflare R2 S3 客户端（零依赖，Node.js 内置）
import crypto from 'crypto';
import {R2} from './r2-config.mjs';
const AK=R2.accessKeyId,SK=R2.secretAccessKey,EP=R2.endpoint,RG=R2.region||'auto',SV='s3';
if(!AK||!SK||!EP)throw new Error('R2 凭据未配置');
const sh=(d)=>crypto.createHash('sha256').update(d).digest('hex');
const hm=(k,d)=>crypto.createHmac('sha256',k).update(d).digest();
const hx=(k,d)=>crypto.createHmac('sha256',k).update(d).digest('hex');
const sk=(k,d,r)=>{let a=hm('AWS4'+k,d),b=hm(a,r),c=hm(b,SV);return hm(c,'aws4_request')};
function sr(m,p,q,h,b){const n=new Date(),am=n.toISOString().replace(/[:-]|\.\d{3}/g,''),dt=am.slice(0,8),ph=b?sh(b):'UNSIGNED-PAYLOAD',hd={'host':EP,'x-amz-content-sha256':ph,'x-amz-date':am,...h};if(b)hd['content-type']=hd['content-type']||'application/octet-stream';const ks=Object.keys(hd).sort(),ch=ks.map(k=>`${k}:${hd[k].trim()}`).join('\n'),hs=ks.join(';'),qp=q||'';const cr=[m,p,qp,ch,'',hs,ph].join('\n'),sts=['AWS4-HMAC-SHA256',am,`${dt}/${RG}/${SV}/aws4_request`,sh(cr)].join('\n'),sv=sk(SK,dt,RG),sg=hx(sv,sts);return{...hd,'Authorization':`AWS4-HMAC-SHA256 Credential=${AK}/${dt}/${RG}/${SV}/aws4_request, SignedHeaders=${hs}, Signature=${sg}`,host:EP}}
export async function uploadBuffer(b,k,buf,ct){const p=`/${b}/${encodeURIComponent(k)}`,h=sr('PUT',p,'',{'content-type':ct||'image/webp'},buf),u=`https://${EP}${p}`,r=await fetch(u,{method:'PUT',headers:h,body:buf});if(!r.ok)throw new Error(`R2 upload failed: ${r.status}`);return{key:k,url:`https://${EP}${p}`,bucket:b}}
export async function listObjects(b,px){const qs=`list-type=2&max-keys=100${px?'&prefix='+encodeURIComponent(px):''}`,p=`/${b}/?${qs}`,h=sr('GET',`/${b}/`,qs,{},null),u=`https://${EP}${p}`,r=await fetch(u,{method:'GET',headers:h});if(!r.ok)throw new Error(`R2 list failed: ${r.status}`);const x=await r.text(),o=[],re=/<Contents>([\s\S]*?)<\/Contents>/g;let m;while((m=re.exec(x))){const c=m[1];const k=(c.match(/<Key>([^<]+)<\/Key>/)||[])[1]||'',s=parseInt((c.match(/<Size>(\d+)<\/Size>/)||[])[1]||'0');if(k)o.push({key:k,size:s,lastModified:(c.match(/<LastModified>([^<]+)<\/LastModified>/)||[])[1]||''})}return o}
export function presignedUrl(b,k,ex=3600){const n=new Date(),am=n.toISOString().replace(/[:-]|\.\d{3}/g,''),dt=am.slice(0,8),cr=`${AK}/${dt}/${RG}/${SV}/aws4_request`,hs='host';const qs=`X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=${encodeURIComponent(cr)}&X-Amz-Date=${am}&X-Amz-Expires=${ex}&X-Amz-SignedHeaders=${hs}`,p=`/${b}/${encodeURIComponent(k)}`,c=['GET',p,qs,`host:${EP}`,'',hs,'UNSIGNED-PAYLOAD'].join('\n'),s=['AWS4-HMAC-SHA256',am,`${dt}/${RG}/${SV}/aws4_request`,sh(c)].join('\n'),sv=sk(SK,dt,RG);return`https://${EP}${p}?${qs}&X-Amz-Signature=${hx(sv,s)}`}